### ISSUE TITLE
Mutually exclusive GraphTypeOption

### ISSUE THREAD

**Issue by sudhackar** [emicklei/dot#20]
Currently the options such as strict and digraph are mutually exclusive

https://github.com/emicklei/dot/blob/d7ab2356e483e86e86f12c8ca8e8e73dfcaa35ea/graph_options.go#L24-L26

So something like this won't work

```go
g := dot.NewGraph(dot.Directed, dot.Strict)
```

And this would fail to render from graphviz v2.38 from [here](https://www2.graphviz.org/Packages/stable/windows/10/msbuild/Release/Win32/)

since the output looks like

```dot
strict  {
        n1[label="Hello"];
        n2[label="World"];
        n1->n2;
}
```

Code 

```go 
package main

import (
	"fmt"
	"github.com/emicklei/dot"
)

func main() {
	g := dot.NewGraph(dot.Directed, dot.Strict)
	n1 := g.Node("Hello")
	n2 := g.Node("World")

	g.Edge(n1, n2)

	fmt.Println(g.String())
}
```

**Comment by sudhackar** [comment]
According to https://graphviz.org/doc/info/lang.html

The definition of a graph looks like 
```
graph :  [ strict ] (graph | digraph) [ ID ] '{' stmt_list '}'
```

So the keywords `strict` and `digraph`/`graph`  should be inclusive

**Comment by emicklei** [comment]
feel free to reopen if want to discuss this later.
