### ISSUE TITLE
Escape character issue?

### ISSUE THREAD

**Issue by kevin-peirce** [emicklei/dot#22]
https://github.com/emicklei/dot/blob/966008b949b7b1e69370ec0d95ec6fcd52ba0532/graph.go#L269

Hi - I'm new to GoLang so I might be wrong.  I've been trying to use the "\l" instruction (See page 8 here: https://www.graphviz.org/pdf/dotguide.pdf ).

To get my code to compile I have to escape the "\l" like this "\\l".  I noticed that the output ended up with the escape being retained, meaning it would look this like in the resultant DOT file "\\l" - which would then make the DOT file not be correct.

I found that on line 368 of "graph.go", if I changed the second %q to a %s and added some quotes, then it worked.  Like this:

fmt.Fprintf(b, "%s=\"%s\"", k, m[k])

Like I say, I only started using GoLang yesterday, so there might be a better way to prevent the escape character from appearing.

Thanks.

**Comment by emicklei** [comment]
so you write `\\l` and it shows `\l` but you want the newline to be processed before producing the dot file ?

**Comment by kevin-peirce** [comment]
> so you write `\\l` and it shows `\l` but you want the newline to be processed before producing the dot file ?

In the code as-is yes, as GoLang was complaining about an unrecognised escape character so it needs to be able to handle the "\\".

:)

**Comment by emicklei** [comment]
```
func TestLabelWithEscaping(t *testing.T) {
	di := NewGraph(Directed)
	di.Node("\\l")
	t.Log(di.String())
}
```
shows indeed
```
digraph  {
        	
        	n1[label="\\l"];
        	
        }
```

**Comment by emicklei** [comment]
```

func TestLabelWithEscaping(t *testing.T) {
	di := NewGraph(Directed)
	n := di.Node("without linefeed")
	n.Attr("label", Literal(`"with \l linefeed"`))
	t.Log(di.String())
}
```

at least this works. I will look at `%q - %s` as well

**Comment by emicklei** [comment]
The Go doc states `%q = a single-quoted character literal safely escaped with Go syntax.`
If I would make the change that you suggested, it might break existing program that rely on the safe escaping.

So I suggest you use the Literal expression instead. Let me know if that works for you.

**Comment by kevin-peirce** [comment]
Wow - missed the Literal thing, that works a treat!  Thanks ever so much, and yes that works for me.  Thanks for your time here :)
