### ISSUE TITLE
GraphTypeOptions override each other

### ISSUE THREAD

**Issue by kiambogo** [emicklei/dot#38]
Expectation:
```go
d := dot.NewGraph(dot.Directed, dot.Strict)
```
should return the following DOT:
```dot
strict digraph  {
    ...
}
```

Reality:
```go
d := dot.NewGraph(dot.Directed, dot.Strict)
```
returns the following DOT:
```dot
strict  {
    ...
}
```

This appears to be because the `GraphTypeOption`  only works with a [single option](https://github.com/emicklei/dot/blob/master/graph_options.go#L24), and will overwrite itself if multiple are passed in (in the above example, `strict` is the last argument so is the resulting graph option used).
```go
func (o GraphTypeOption) Apply(g *Graph) {
	g.graphType = o.Name
}
```

**Comment by emicklei** [comment]
thank you for reporting this issue. I will check the DOT rules about this and fix it accordingly.

**Comment by emicklei** [comment]
indeed, the strict is optional:
```
[ strict ] (graph | digraph)
```
