### ISSUE TITLE
Support subgraphs in MermaidGraph

### ISSUE THREAD

**Issue by diwakergupta** [emicklei/dot#39]
The `MermaidGraph` [implementation](https://github.com/emicklei/dot/blob/master/mermaid.go#L64) currently iterates over nodes, but does not factor-in subgraphs, unlike the [dot implementation](https://github.com/emicklei/dot/blob/master/mermaid.go#L64)

Would be awesome if subgraphs were supported in MermaidGraph as well!

**Comment by emicklei** [comment]
try out https://github.com/emicklei/dot/commit/95cd1ec05142389c72ea2522e6064426eeee90d2

**Comment by diwakergupta** [comment]
Seems to work in my basic testing, thanks for the fast turnaround!
